# config/settings.yaml

# Основные настройки AutoDrawer
target_width: 100               # Целевая ширина изображения (пиксели или ячейки, целое число > 0)
num_colors: 10                  # Ожидаемое количество цветов в палитре (целое число, обычно 5-20)
click_delay: 0.5                # Задержка между кликами рисования (сек, > 0)
color_change_delay: 0.08        # Задержка при смене цвета (сек, > 0)
clear_click_delay: 0.5          # Задержка между кликами ластика (сек, > 0)
failsafe_delay: 0.01            # Минимальная задержка для pyautogui (сек, > 0)

# Настройки детектора холста
canvas_detection:
  search_offset_y_ratio: 0.3    # Доля экрана сверху, исключаемая из поиска (0.0-1.0, обычно 0.2-0.5)
  adaptive_thresh_block_size: 11 # Размер блока для адаптивной пороговой обработки (нечетное целое число, > 3)
  adaptive_thresh_c: 2           # Константа вычитания для адаптивного порога (целое число, обычно 0-10)
  morph_kernel_size: 3          # Размер ядра для морфологических операций (нечетное целое число, обычно 3-5)
  morph_iterations: 1           # Количество итераций морфологической обработки (целое число, обычно 1-3)
  cell_min_aspect_ratio: 0.8    # Минимальное соотношение сторон ячейки (0.5-1.0)
  cell_max_aspect_ratio: 1.2    # Максимальное соотношение сторон ячейки (1.0-2.0)
  cell_min_width: 5             # Минимальная ширина ячейки (пиксели, > 0)
  cell_max_width: 100           # Максимальная ширина ячейки (пиксели, > cell_min_width)
  cell_min_height: 5            # Минимальная высота ячейки (пиксели, > 0)
  cell_max_height: 100          # Максимальная высота ячейки (пиксели, > cell_min_height)
  assume_portrait: true         # Корректировать ориентацию сетки для портретного режима (true/false)
  fallback_cell_size: 20        # Размер ячейки по умолчанию, если детекция не удалась (пиксели, > 0)