# Основные настройки AutoDrawer
target_width: 100        # Целевая ширина изображения (в пикселях или ячейках)
num_colors: 10           # Ожидаемое количество цветов в палитре
click_delay: 0.5         # Задержка между кликами рисования (сек)
color_change_delay: 0.08 # Задержка при смене цвета (сек)
clear_click_delay: 0.5   # Задержка между кликами ластика (сек)
failsafe_delay: 0.01     # Минимальная задержка для pyautogui (сек)